vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set relativenumber")
vim.cmd("set number")
vim.cmd("set numberwidth=3")
vim.cmd("hi! link EndOfBuffer Ignore")
vim.cmd("set cursorline")
